### ISSUE TITLE
[认领翻译]chapter03-item11

### ISSUE THREAD

**Issue by VonJane** [learning-and-thinking/Effective-Java-3rd-Edition-zh#27]
[认领翻译]chapter03-item11

**Comment by Angus-Liu** [comment]
感谢你的支持 : )

**Comment by Angus-Liu** [comment]
朋友，你好，由于我之前的疏忽，没有将成员翻译好的第11条合并进总分支，目前和你的翻译起了冲突，想知道你目前的翻译进度如何。如果翻译还没开始，我可以把第11条合并进分支，你可以以校对的方式重新认领。实在是抱歉。目前Effective Java第三版中文版已经发行了，但本项目还不会关闭，接下来会以学习交流的方式进行，若你愿意，欢迎继续参与 : )。

**Comment by VonJane** [comment]
好的，我目前翻译进度差不多三分之一。还是很少的，还是保留其他成员的版本吧。最近翻译的进度比较慢，时间不太多。本项目如果不关闭的话我还是有兴趣在工作以外的时间尽量拿出一部门来学习交流的。
